name: tail.writer
author: SamBrishes
category: Forms
tags: [editor, markdown, github flavored, gfm, text, textarea]
docs: https://github.com/pytesNET/tail.writer/
demo: https://pytesnet.github.io/tail.writer/
current: 0.2.0